// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Home": {
    "title": "Início",
    "welcome": "Gilberto Junior",
    "description": "Engenheiro de Software & Especialista em IA",
    "cta_primary": "Entre em contato",
    "cta_secondary": "Conheça meu trabalho",
    "scroll": "Rolar para baixo",
    "scroll_aria": "Rolar para a seção sobre",
    "exploreMore": "Explore Mais"
  },
  "About": {
    "title": "Sobre Mim",
    "subtitle": "Quem sou",
    "welcome": "Conheça minha história e experiência",
    "founded": "Mais de 20 anos de experiência",
    "who": "Sou um engenheiro de software com mais de 20 anos de experiência em arquitetura, desenvolvimento full-stack e automação com foco em inteligência artificial.",
    "p1": "Atualmente, utilizo intensamente IDEs com inteligência artificial generativas de código para acelerar entregas de alto impacto, atuando quase exclusivamente na criação de funcionalidades assistidas por IA.",
    "p2": "Utilizo IA como copiloto em praticamente todas as entregas. Desde o design de funcionalidades até o deploy, passando por refatorações, integrações de APIs, geração de testes e pipelines.",
    "skill1_title": "Engenharia de Software",
    "skill1_desc": "Engenharia de software moderna (SOLID, TDD, DDD, Clean Architecture)",
    "skill2_title": "Desenvolvimento Web",
    "skill2_desc": "Desenvolvimento com foco em integração com inteligência artificial",
    "skill3_title": "Infraestrutura Cloud",
    "skill3_desc": "Infraestrutura com AWS, CI/CD, Docker, Kubernetes",
    "skill4_title": "Inteligência Artificial",
    "skill4_desc": "Integrações com modelos e fluxos de IA generativa para automatizar processos",
    "skills_title": "Minhas Habilidades",
    "tech_title": "Tecnologias",
    "backToHome": "Voltar para a página inicial"
  },
  "Services": {
    "title": "Meus Serviços",
    "welcome": "Soluções que ofereço",
    "subtitle": "O que faço",
    "description": "Serviços de desenvolvimento com foco em inteligência artificial",
    "service1": "Sistemas com IA Integrada",
    "service1Desc": "Desenvolvimento de sistemas inteligentes com integração de LLMs e IA generativa para automação de processos.",
    "service2": "Plataformas SaaS",
    "service2Desc": "Criação de plataformas SaaS com backends performáticos e arquitetura escalável.",
    "service3": "Aplicações Web Modernas",
    "service3Desc": "Desenvolvimento de serviços web, seguindo práticas modernas de engenharia de software.",
    "service4": "Consultoria em IA",
    "service4Desc": "Consultoria para implementação de fluxos de trabalho assistidos por IA e automação de processos com OpenAI.",
    "cta": "Entre em contato para discutir seu projeto",
    "backToHome": "Voltar para a página inicial"
  },
  "Contact": {
    "title": "Entre em Contato",
    "subtitle": "Contato",
    "welcome": "Tem um projeto em mente ou precisa de ajuda com uma solução de software? Entre em contato comigo para discutirmos como posso ajudar.",
    "description": "Entre em contato para discutir seu projeto ou tirar dúvidas",
    "name": "Nome",
    "email": "Email",
    "subject": "Assunto",
    "message": "Mensagem",
    "send": "Enviar Mensagem",
    "sending": "Enviando...",
    "required": "Este campo é obrigatório",
    "invalidEmail": "Por favor, insira um email válido",
    "namePlaceholder": "Seu nome",
    "emailPlaceholder": "Seu email",
    "subjectPlaceholder": "Assunto da mensagem",
    "backToHome": "Voltar para a página inicial",
    "messagePlaceholder": "Sua mensagem",
    "successMessage": "Mensagem enviada com sucesso! Entrarei em contato em breve.",
    "errorMessage": "Erro ao enviar mensagem. Por favor, tente novamente.",
    "languages": "Idiomas",
    "languages_list": "Português (Nativo), Inglês (Avançado)",
    "location": "Localização",
    "phone": "Telefone"
  },
  "Navigation": {
    "home": "Início",
    "about": "Sobre Mim",
    "services": "Serviços",
    "experience": "Experiência",
    "portfolio": "Portfólio",
    "contact": "Contato"
  },
  "Footer": {
    "title": "Rodapé",
    "description": "Transforme suas ideias em soluções guiadas por IA e experiência profissional.",
    "quickLinks": "Links Rápidos",
    "contact": "Contato",
    "address": "Vera Cruz - SP, Brasil",
    "phone": "+55 11 98765-4321",
    "email": "contato@codehappy.com.br",
    "rights": "Todos os direitos reservados.",
    "company": "Code Happy Tecnologia Ltda",
    "social": "Redes Sociais",
    "github": "GitHub",
    "linkedin": "LinkedIn"
  },
  "Experience": {
    "title": "Plataformas SaaS de Destaque",
    "subtitle": "Projetos de impacto",
    "welcome": "Maiores projetos onde eu participei",
    "project1_title": "Jarvi.io",
    "project1_desc": "",
    "project2_title": "HelloFatima.com",
    "project2_desc": "",
    "project3_title": "Tray.com.br",
    "project3_desc": "",
    "current_focus": "Foco Atual",
    "current_focus_desc": "Meu foco está em desenvolver sistemas SaaS escaláveis com inteligência artificial integrada, utilizando arquiteturas modernas e práticas de DevOps para garantir alta disponibilidade e performance."
  },
  "Skills": {
    "title": "Minhas Habilidades",
    "subtitle": "Competências",
    "welcome": "Tecnologias e ferramentas que domino"
  },
  "CodeHappy": {
    "title": "Code Happy",
    "subtitle": "Desenvolvimento",
    "welcome": "Desenvolvimento de software com foco em qualidade e produtividade"
  },
  "Success": {
    "title": "Mensagem enviada!",
    "message": "Obrigado pelo contato. Sua mensagem foi enviada com sucesso e retornarei em breve.",
    "backHome": "Voltar para o início"
  }
};
export default messages;